[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "motep"
version = "0.1.0"
dependencies = [
    "ase",
    "mpi4py",
    "scipy",
]
requires-python = ">=3.11"  # tomllib
authors = [
    {name = "Pranav Kumar"},  # trainer
    {name = "Axel Forslund"},  # calculator
    {name = "Yuji Ikeda"},  # testing
]

[project.scripts]
motep = "motep.__init__:main"

[tool.setuptools]
packages = ["motep"]

[tool.ruff.lint]
preview = true  # necessary to activate many pycodestyle rules
select = ["ALL"]
