configurations = 'training.cfg'
potential_initial = 'initial.mtp'
potential_final = 'final.mtp'
seed = 10
energy-weight = 1.0
force-weight = 0.01
stress-weight = 0.0

[[steps]]
method = 'NI'
optimized = ['species_coeffs']
[[steps]]
method = 'randomize'
optimized = ['moment_coeffs', 'radial_coeffs']
[[steps]]
method = 'LLS'
optimized = ['moment_coeffs']
minimized = ['energy', 'forces']
[[steps]]
method = 'Nelder-Mead'
optimized = ['radial_coeffs', 'moment_coeffs']
